# Generated by Django 6.0.6 on 2026-06-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("image", models.URLField()),
                ("year", models.TextField(max_length=4)),
                ("model", models.CharField(max_length=30)),
                ("starting_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("milespergalon", models.IntegerField()),
                ("horsepower", models.IntegerField()),
                ("rating", models.DecimalField(decimal_places=1, max_digits=1)),
            ],
        ),
    ]
