# Generated by Django 6.0.6 on 2026-06-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="rating",
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name="car",
            name="starting_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
